name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask Flask-Caching Flask-Limiter bandit

      - name: Run Bandit for security checks
        run: bandit -r . -f json -o bandit_report.json

      - name: Upload Bandit report
        uses: actions/upload-artifact@v2
        with:
          name: bandit_report
          path: bandit_report.json
